### ISSUE TITLE
Out Of Memory Error while browsing the map vault

### ISSUE THREAD

**Issue by Justify87** [FAForever/downlords-faf-client#1104]
java.util.concurrent.CompletionException: java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.OutOfMemoryError: Java heap space

[downlords-faf-client.zip](https://github.com/FAForever/downlords-faf-client/files/2832237/downlords-faf-client.zip)

I clicked on "Load more" to show more maps. A few secs after the second click in that button the error above showed up.

**Comment by Brutus5000** [comment]
Can you reproduce this? How many times did you click on load more? How much memory has your system?
(By the way this is the reason why the local replay vault is limited to 300 records - in a bad way though)

**Comment by Justify87** [comment]
For reprododuction:
- Go to map vault
- Dont' search for anything
- Click on this (newst maps):
![grafik](https://user-images.githubusercontent.com/10554299/52474053-a3392c80-2b97-11e9-97a5-9b2e7cf4e4c4.png)
- the second clicks on this button will trigger the error
![grafik](https://user-images.githubusercontent.com/10554299/52474114-d1b70780-2b97-11e9-8bba-9a54669e87ce.png)

I have 500GB of SSD ROM and 16GB of RAM
about 10GB of RAM were not in use when this error was thrown and I have plenty of free space on my SSD.

I noticed though that after clicking on this:
![grafik](https://user-images.githubusercontent.com/10554299/52474053-a3392c80-2b97-11e9-97a5-9b2e7cf4e4c4.png)
The whole client already felt sluggish even before the error was thrown.

**Comment by Brutus5000** [comment]
I tried to reproduce this. Everything works. The client memory sticks between 1,0 and 1,1 GB RAM. This should not be a problem on a 16GB RAM machine.

**Comment by 1-alex98** [comment]
The more button is known to cause probelems. We want to make proper paging one day...

**Comment by Katharsas** [comment]
I can reproduce this (0.10.7-RC1) for "most recent" by clicking 'more' button 3 times, i will have a look into this. Does anybody know how large these preview images are? Heapdump should show the problem i guess.

<details>
  <summary>(btw:)</summary><p>
  On my local build it sometimes doesn't crash but simply hangs up after like 10 times "load more" while spewing out tons of these:

```
java.lang.NullPointerException
	at javafx.graphics/com.sun.prism.d3d.D3DTexture.getContext(D3DTexture.java:84)
	at javafx.graphics/com.sun.prism.d3d.D3DTexture.update(D3DTexture.java:207)
	at javafx.graphics/com.sun.prism.d3d.D3DTexture.update(D3DTexture.java:151)
	at javafx.graphics/com.sun.prism.impl.BaseContext.flushMask(BaseContext.java:109)
	at javafx.graphics/com.sun.prism.impl.BaseContext.drawQuads(BaseContext.java:118)
	at javafx.graphics/com.sun.prism.impl.VertexBuffer.flush(VertexBuffer.java:98)
	at javafx.graphics/com.sun.prism.impl.BaseContext.flushVertexBuffer(BaseContext.java:101)
	at javafx.graphics/com.sun.prism.impl.ps.BaseShaderContext.setRenderTarget(BaseShaderContext.java:746)
	at javafx.graphics/com.sun.prism.impl.BaseContext.setRenderTarget(BaseContext.java:131)
	at javafx.graphics/com.sun.prism.impl.BaseGraphics.<init>(BaseGraphics.java:106)
	at javafx.graphics/com.sun.prism.impl.ps.BaseShaderGraphics.<init>(BaseShaderGraphics.java:86)
	at javafx.graphics/com.sun.prism.d3d.D3DGraphics.<init>(D3DGraphics.java:42)
	at javafx.graphics/com.sun.prism.d3d.D3DGraphics.create(D3DGraphics.java:65)
	at javafx.graphics/com.sun.prism.d3d.D3DSwapChain.createGraphics(D3DSwapChain.java:134)
	at javafx.graphics/com.sun.javafx.tk.quantum.PresentingPainter.run(PresentingPainter.java:87)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at javafx.graphics/com.sun.javafx.tk.RenderJob.run(RenderJob.java:58)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

and then tons of these:<br>
```
java.lang.NullPointerException<br>
java.lang.NullPointerException<br>
java.lang.NullPointerException<br>
java.lang.NullPointerException<br>
```
</p></details>

Edit:
The image sizes for the MapCards (not the Map detail view) seem to mostly be 512x512px with some 256 or 128 in between (for the first more page of 'most liked'). 

Edit2:
When making a heapdump after clicking 'more', a bunch of times, the heapdump analyzer tells me:
```
Total: 807,6 MB
742 instances of "com.sun.prism.Image", loaded by
"jdk.internal.loader.ClassLoaders$PlatformClassLoader @ 0x6c2fb3688"
occupy 606.451.416 (71,61 %) bytes. These instances are referenced from
one instance of "javafx.beans.value.ChangeListener[]"
```
Edit3:
- Per 'more' page 5x20 additional MapCards are shown
- As far as i can see the number of `com.sun.prism.Image` instances is equal to the number of shown MapCards, so everything seems to be ok in that regard (no multiple copies of the same preview in memory)

Edit4:
When using VisualVM to monitor heap size, i get a total size of 536MB after clicking 'more' twice. Of of that, 486MB are used. This means it is no wonder that i and Morax and others get an out of memory esxception, because the max heap size is specified at 512MB, which won't be enough to load 100 more images on the next 'more' click.

What is interesting though:
When making a heap dump in this situation (486MB used heap), the exported heap dump will only have a size of 290MB. From what i understand, this means that **196MB / 40% of heap size are not in the heap dump**, for example because that memory is used by native code like the JavaFX Direct3D Hardware Renderer (which runs in the background of this client when using windows).

I VERY MUCH suspect that every image is in memory twice: Once in the java heap and once as D3D buffer for copying the images to the GPU. This would also line up with expected image sizes: If we guess that 220 images are loaded, the expected memory usage for that is 170MB, which lines up exactly with what the heap dump tells me and they would also fit perfectly into the mysterious 196MB of heap that is not part of the dump.

**Comment by Katharsas** [comment]
Btw, on my local build it doesn't crash but simply hangs up after like 10 times "load more" while spewing out tons of these:
```
java.lang.NullPointerException
	at javafx.graphics/com.sun.prism.d3d.D3DTexture.getContext(D3DTexture.java:84)
	at javafx.graphics/com.sun.prism.d3d.D3DTexture.update(D3DTexture.java:207)
	at javafx.graphics/com.sun.prism.d3d.D3DTexture.update(D3DTexture.java:151)
	at javafx.graphics/com.sun.prism.impl.BaseContext.flushMask(BaseContext.java:109)
	at javafx.graphics/com.sun.prism.impl.BaseContext.drawQuads(BaseContext.java:118)
	at javafx.graphics/com.sun.prism.impl.VertexBuffer.flush(VertexBuffer.java:98)
	at javafx.graphics/com.sun.prism.impl.BaseContext.flushVertexBuffer(BaseContext.java:101)
	at javafx.graphics/com.sun.prism.impl.ps.BaseShaderContext.setRenderTarget(BaseShaderContext.java:746)
	at javafx.graphics/com.sun.prism.impl.BaseContext.setRenderTarget(BaseContext.java:131)
	at javafx.graphics/com.sun.prism.impl.BaseGraphics.<init>(BaseGraphics.java:106)
	at javafx.graphics/com.sun.prism.impl.ps.BaseShaderGraphics.<init>(BaseShaderGraphics.java:86)
	at javafx.graphics/com.sun.prism.d3d.D3DGraphics.<init>(D3DGraphics.java:42)
	at javafx.graphics/com.sun.prism.d3d.D3DGraphics.create(D3DGraphics.java:65)
	at javafx.graphics/com.sun.prism.d3d.D3DSwapChain.createGraphics(D3DSwapChain.java:134)
	at javafx.graphics/com.sun.javafx.tk.quantum.PresentingPainter.run(PresentingPainter.java:87)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at javafx.graphics/com.sun.javafx.tk.RenderJob.run(RenderJob.java:58)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
	at java.base/java.lang.Thread.run(Thread.java:844)
```
and then tons of these:
```
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
```

**Comment by Katharsas** [comment]
My Conclusion to what needs to happen:
- Reduce number of images (proper paging or virtual list to unload images not in view currently)
- Reduce resolution to what is needed (256px is 4 times smaller than 512, which is much better)
- Whenever images are loaded, there is a massive increase in heap size, and a lot of that increase (almost half) does not come from java code (but probably from native JavaFX code). We probably cannot do much about this unless we use software rendering or something (if that is even possible in javafx). Maybe there is a way to pass image file paths to JavaFX without even creating images in hava heap memory but i don't know.


Image where you can see massive heap increases whenever 'more' click happens:
![Capture](https://user-images.githubusercontent.com/1922573/60066901-d9231b80-9708-11e9-803e-f3170932d580.JPG)

**Comment by 1-alex98** [comment]
heap space is limited to 512 mb

**Comment by 1-alex98** [comment]
Clicking the more button is probably just the trigger the memory was probably filled up with other shit before

**Comment by Katharsas** [comment]
Trigger? Clicking more a third time is exactly when the client tries to exceed the 512 mb limit and throws OutOfMemory due to all the images it needs to load and has already loaded.

Btw i also did a memory dump with image loading entirly disabled for MapCards, and in that case you will hit CPU problems (100%, eventually freezing the entire client) long before running into RAM problems, so it really is the images.

**Comment by Katharsas** [comment]
Some maybe useful information about the image sizes, so that it is not lost even if this is not pursued further (Note: I don't currently plan on implementing this):

Currently, the content server can provide each map picture in too versions:
- big: 512x512px or lower (can be 256 or 128 for some pictures)
- small: 128x128px

Currently, the big pictures are used for all map previews.

Then, there are too more versions for each map, but with big mex / hydro symbols on them. I haven't looked into these, they are propbably used by game list.

Some things that one could think about:
- Do nothing server side but scale down 512px images after download and have both 512px and scaled 256px images in disk cache. Load needed size to RAM.
- Instead of providing 512px and 128px, provide 512px and 256px on server, so that the small ones can be used in more places (pretty much all places except very big lobby preview). If the game list view currently uses the 128px ones (not sure), this would increase RAM usage in games list by 4x (from 1MB to 4MB raw image data when 20 games are in list)
- Same server change as above but additionally scale 256px images down to 128 when small ones are needed and cache on disk
- Provide all 3 sizes on server (512, 256, 128) and cache all on disk
- Let server provide only a single MipMap kinda image that contains all 3 sizes and is cached on disk. Load only the needed subsections to RAM (there should be libs for this).

Data Deduplication:
Its a waste to have map images twice, once with big mex symbols and once without. A better solution would be to only store positional data from mex and hydro spots and overlay big symbols on top of  a normal map image on the fly (hoewever not sure if this would work with in-game lobby). This probably won't affect RAM very much though (since i guess these pictures are only loaded when joining a lobby). However, this might synergize with adaptive maps (being able to hide/show disabled mex spots)

Architecture:
If the server side is touched anyway, it may make sense to discuss high level architecture (content server vs API, files vs image db).

**Comment by Brutus5000** [comment]
Should be fixed by #1320

**Comment by 1-alex98** [comment]
mod vault still missing tho not sure if we have issues for this

**Comment by Katharsas** [comment]
Due to the low number of images in the mod vault it probably doesn't cause problems in the same way. But yeah, it should receive the pagination treatment too, new issue is probably best.
