### ISSUE TITLE
no aeolus messages are shown

### ISSUE THREAD

**Issue by JaggedAppliance** [FAForever/downlords-faf-client#1265]
![chatbug](https://user-images.githubusercontent.com/5166284/58096819-d6934a80-7bcd-11e9-82a1-23e18be76447.png)
[downlords-faf-client.log](https://github.com/FAForever/downlords-faf-client/files/3202529/downlords-faf-client.log)
No aeolus messages show up for me, not even my own. I was watching aeolus through discord and saw that my messages and others were getting posted to aeolus normally.

**Comment by 1-alex98** [comment]
Nothing in log

**Comment by JaggedAppliance** [comment]
This was fixed by restarting the client btw

**Comment by 1-alex98** [comment]
Well this issue is ancient and a lot hase changed since reopen if issue persists
