### ISSUE TITLE
Launching coop replay leads to ingame error

### ISSUE THREAD

**Issue by Katharsas** [FAForever/downlords-faf-client#1312]
Client version 0.10.7-RC1
Game starts with black screen and shows a small dialog:
```
Ack!

Unable to load game replay from
C:\ProgramData\FAForever\cache\temp.scfareplay
[ Ok ]
```
Clicking ok will play the intros and then open the main menu of SCFA.

Happens for all my recent coop replays i think like this one:
[9793951-Katharsas.zip](https://github.com/FAForever/downlords-faf-client/files/3318738/9793951-Katharsas.zip)

**Comment by Katharsas** [comment]
Ok so it seems like others can reproduce with the given replay. Can somebody check if this happens for other replays that where played before game patch 3704 as well?

**Comment by speed2CZ** [comment]
It happens to all coop replays I tried.
Those replays work when launched via python client

**Comment by 1-alex98** [comment]
Did not happen to all i tried. I found some that were working

**Comment by speed2CZ** [comment]
New ones, old one? Can you give some ID?

**Comment by 1-alex98** [comment]
sec

**Comment by 1-alex98** [comment]
![image](https://user-images.githubusercontent.com/19996713/60382358-449b1f00-9a62-11e9-8263-2a8cb557d893.png)

**Comment by 1-alex98** [comment]
this one works for example

**Comment by Syr3L** [comment]
for me this one seems to be not working (anymore) ...

**Comment by Syr3L** [comment]
i think i might have found out why this aint workin?!? 
I've opend the tmp.fafreplay file in notpad++ and wht seems to be containing a json string it states:
`
"featured_mod_versions": {
		"1": 55,
		"2": 55,
		"3": 49,
		"4": 49,
                .
                .
                .
`
seems its a modded game?
i start with no mods?!?  maybe out of date?
hope info helps

P.S.Edit: 
Grabbed ReplayID from Logs:
`info: REPLAY ID: 9473048`

Another id would be: 9500465 for another CooP Replay

**Comment by 1-alex98** [comment]
should be fixed

**Comment by Katharsas** [comment]
Reminder to myself to test this.

**Comment by Katharsas** [comment]
Its fixed for any recently created replays (for me the oldest fixed replay is from 15.02.2020), but all older replays are still broken with same error.

**Comment by Sheikah45** [comment]
Should be fixed with #1866
