### ISSUE TITLE
[Bug]: Cannot enter/create games

### ISSUE THREAD

**Issue by pavukach** [FAForever/downlords-faf-client#3261]
### Describe the Bug

When i try to create or enter game i get log with EXCEPTION_ACCESS_VIOLATION

### Log file or Error Message

https://github.com/FAForever/downlords-faf-client/releases/download/v2024.6.2/faf_unix_2024_6_2.tar.gz

### Reproduce the bug

1. download client from aur
2. log in
3. try to create game in custom games (to not bother thers)

### Expected Behavior

Expected: Launcher opens game
Actual: Crash log opens

### Additional context

I am on cachyos, so i use their wine, proton and etcetera

### Which Operating System are you using?

Linux

**Comment by veqqq** [comment]
It has become global. No one can play now.

**Comment by pavukach** [comment]
> It has become global. No one can play now.

i dont see literally anyone saying about it. but, anyway, if so, should we wait for fix or what?

**Comment by veqqq** [comment]
> > It has become global. No one can play now.
> 
> i dont see literally anyone saying about it. but, anyway, if so, should we wait for fix or what?

2-4 days ago, everyone was saying it in IRC and there were no custom games. There was a get 500 issue for some reason and a few other random things someone found. I assumed it was a server issue. As of yesterday, what I meant was fixed. I'm not sure about the top guy.

**Comment by pavukach** [comment]
> 2-4 days ago, everyone was saying it in IRC and there were no custom games. There was a get 500 issue for some reason and a few other random things someone found.
unfortunatelly is not mine, this one still persists (it is not server side issue in my case)

**Comment by veqqq** [comment]
Check Steam, there was a recent to the actual game, besides the supporting libraries. Also did you update the client?

**Comment by olafurkarl** [comment]
I'm also having this issue on a fresh install of the game.

Crash log:

[faf_crash_log.txt](https://github.com/user-attachments/files/19070179/faf_crash_log.txt)

edit: I ran `./setup.sh` again, and `./set-client-paths.sh`, which seems to have resolved this. 👍
